before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths: [vendor/*]

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd:
        enabled: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
        excluded_dirs: [vendor]
    php_analyzer:
        enabled: true
    sensiolabs_security_checker: true
